### ISSUE TITLE
Warning for light not allowed to be 0

### ISSUE THREAD

**Issue by zacs** [jvmahon/homebridge-hubitat#17]
I just upgraded Homebridge to 1.3.1 and am getting this error:

`[homebridge-hubitat] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://git.io/JtMGR for more info.`

It doesn't seem to impact anything all that much. I can't tell which device is causing it, but all works well after the warning.

**Comment by jvmahon** [comment]
Please update your plugin to 1.0.7 and hopefully that will fix it.

**Comment by zacs** [comment]
Appreciate the fast response! Just upgraded and got the warning again. I was vague in my original title, and this is related to a brightness sensor. 

```
[3/1/2021, 8:19:38 PM] [homebridge-hubitat] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://git.io/JtMGR for more info.
```

That said, it looks like you already handle it correctly here: https://github.com/jvmahon/homebridge-hubitat/blob/ac46eb159c087374e63e09f0218bffe921c765cd/lib/Setup%20Sensors.js#L85

**Comment by jvmahon** [comment]
I'm confused - after installing 1.0.7 is it working correctly or not? I think it should be fixed so if it isn't, I'm not sure why.

**Comment by zacs** [comment]
It is not fixed. I'm just saying that I also am not sure why. Unless `CurrentAmbientLightLevel.props.minValue` is incorrectly defined, your code (the L85 I linked) should handle things just fine. 

Not a big deal, just a warning, and Homebridge appears to set it to 0.0001 when it catches the warning.

**Comment by jvmahon** [comment]
No clue why this could be happening as the check I added should ensure the value is within the permitted bounds.

I have noted, on rare occasion, that when I do an npm update, sometimes the cached code doesn't properly clear, so if this problem continues, you may want to uninstall the plugin, clear the cache (on Windows, that's at:  
`````
C:\Users\[YOUR LOGIN NAME]\AppData\Roaming\npm-cache
`````
and then re-install the plugin.

I'm closing this issue for now. Re-open if the problem continue and maybe someone else will have a suggestion (I'm not sure what else I can do at this point).
